import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/core/theme/theme-provider";
import { Roboto } from 'next/font/google'
import PageTheme from "@/core/theme/layout-theme";


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "zagros",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className={`${roboto.className} bodyWithSidebar font-display`}>
        <ThemeProvider>
          <PageTheme>
            {children}
          </PageTheme>
        </ThemeProvider>
      </body>

    </html>
  );
}
