import type { Metadata } from "next";
import SidebarDrawer from "@/components/layout/side-bar";
import dynamic from "next/dynamic";

const MainHeader = dynamic(
    () => import("@/components/layout/main-header"),
    { ssr: false }
)

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div className="flex hide-scrollbar min-h-screen">
            <SidebarDrawer />
            <MainHeader />
            <main className=" pt-36 w-full  p-4">
                {children}
            </main>
        </div>

    );
}
