import type { Metadata } from "next";
import SidebarDrawer from "@/components/layout/side-bar";
import MainHeader from "@/components/layout/main-header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div className="flex h-full min-h-screen">
            <SidebarDrawer />

            <MainHeader />
            <main className="flex-grow pt-36 w-full relative box-border  p-4">
                {children}
            </main>
        </div>

    );
}
